### PR TITLE
support for image attachments and improvements for the CI services

### PR DESCRIPTION
**Pull request by fczuardi**
This change is [Reviewable](https://reviewable.io/reviews/calamar-io/calamars/22)

### CODE REVIEW

**Comment by fredmarques** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/facebook.js, line 237 \[r1\]](https://reviewable.io:443/reviews/calamar-io/calamars/22#-KJuQ_jT9j092v36o2vH:-KJuQ_jT9j092v36o2vI:-1679916623) ([raw file](https://github.com/calamar-io/calamars/blob/e2997bacc7a75b912d5d8afa74936112708478e3/test/facebook.js#L237)):*
> ```JavaScript
> });
> 
> test.only('Bot sends a long text message', async t => {
> ```

Remove `.only`. All tests should run.

---

*[test/facebook.js, line 260 \[r1\]](https://reviewable.io:443/reviews/calamar-io/calamars/22#-KJuQA9ftLCImxXvmjAT:-KJuQA9ftLCImxXvmjAU:-1679916623) ([raw file](https://github.com/calamar-io/calamars/blob/e2997bacc7a75b912d5d8afa74936112708478e3/test/facebook.js#L260)):*
> ```JavaScript
> });
> 
> test.only('Bot sends a message with image attachment', async t => {
> ```

Remove `.only`. All tests should run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/calamar-io/calamars/22)*

**Comment by fczuardi** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/facebook.js, line 237 \[r1\]](https://reviewable.io:443/reviews/calamar-io/calamars/22#-KJuQ_jT9j092v36o2vH:-KJvSqkfK9Iwlt8qXMrA:-1244989619) ([raw file](https://github.com/calamar-io/calamars/blob/e2997bacc7a75b912d5d8afa74936112708478e3/test/facebook.js#L237)):*
<details><summary><i>Previously, fredmarques (Frederico Marques) wrote…</i></summary>
> Remove `.only`. All tests should run.
</details>
good catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/calamar-io/calamars/22)*

**Comment by fczuardi** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/facebook.js, line 237 \[r1\]](https://reviewable.io:443/reviews/calamar-io/calamars/22#-KJuQ_jT9j092v36o2vH:-KJvTrbChvKHxn6lc280:-467915377) ([raw file](https://github.com/calamar-io/calamars/blob/e2997bacc7a75b912d5d8afa74936112708478e3/test/facebook.js#L237)):*
<details><summary><i>Previously, fczuardi (Fabricio C Zuardi) wrote…</i></summary>
> good catch
</details>
fixed

---

*[test/facebook.js, line 260 \[r1\]](https://reviewable.io:443/reviews/calamar-io/calamars/22#-KJuQA9ftLCImxXvmjAT:-KJvTwbrQtgJ-tLfDCn_:-467915377) ([raw file](https://github.com/calamar-io/calamars/blob/e2997bacc7a75b912d5d8afa74936112708478e3/test/facebook.js#L260)):*
<details><summary><i>Previously, fredmarques (Frederico Marques) wrote…</i></summary>
> Remove `.only`. All tests should run.
</details>
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/calamar-io/calamars/22)*

**Comment by fczuardi** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/facebook.js, line 237 \[r1\]](https://reviewable.io:443/reviews/calamar-io/calamars/22#-KJuQ_jT9j092v36o2vH:-KJvU1Ww6YuRUPUXdJo5:-499146009) ([raw file](https://github.com/calamar-io/calamars/blob/e2997bacc7a75b912d5d8afa74936112708478e3/test/facebook.js#L237)):*
<details><summary><i>Previously, fczuardi (Fabricio C Zuardi) wrote…</i></summary>
> fixed
</details>
Done.

---

*[test/facebook.js, line 260 \[r1\]](https://reviewable.io:443/reviews/calamar-io/calamars/22#-KJuQA9ftLCImxXvmjAT:-KJvU2X-T7pvpRYP2V4l:-499146009) ([raw file](https://github.com/calamar-io/calamars/blob/e2997bacc7a75b912d5d8afa74936112708478e3/test/facebook.js#L260)):*
<details><summary><i>Previously, fczuardi (Fabricio C Zuardi) wrote…</i></summary>
> fixed
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/calamar-io/calamars/22)*

**Comment by fredmarques** [comment]
Reviewed 6 of 9 files at r2.
Review status: 7 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/calamar-io/calamars/22)*

**Comment by fredmarques** [comment]
Reviewed 1 of 9 files at r2.
Review status: 8 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/calamar-io/calamars/22)*

**Comment by fredmarques** [comment]
Reviewed 1 of 9 files at r2.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/calamar-io/calamars/22)*

**Comment by fredmarques** [comment]
Reviewed 1 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/calamar-io/calamars/22)*

**Pull request merged**
